In [7]:
import numpy as np
import pandas as pd
import plotly.express as ex
import scipy.linalg as la
from scipy.fftpack import dct



In [ ]:
def pca(M):
    cov = M.T @ M
    s, u = la.eigh(cov)
    return lambda k: u[:, -k:] @ M

def dct(M):
    m = np.reshape(M, (-1))
    D = dct(np.eye(m.shape[0]), axis=0)
    u = 
    return lambda 
    

In [12]:
a = np.ones((2,5))
b = np.reshape(a, (-1))

In [18]:
D = dct(np.eye(3), axis=0)
D

array([[ 2.        ,  2.        ,  2.        ],
       [ 1.73205081,  0.        , -1.73205081],
       [ 1.        , -2.        ,  1.        ]])

In [26]:
e = np.eye(3)
e2 = np.reshape(e, (-1))
k = 0
s = np.arange(e2.size)
s2 = (np.arange(e2.size)+0.5) * (np.pi/e2.size)
for i in range(e2.shape[0]):
    e2[i] = np.sum(e2 * np.cos(s2*i))
e2.reshape(e.shape)

array([[ 3.        ,  1.96961551,  3.74357824],
       [-1.50998305, -0.70064863, -3.18758402],
       [ 0.25403871,  1.33648768,  5.81751384]])

In [27]:
e = np.eye(3)
k = 0
for i in range(e.shape[0]):
    e2 = e[i]
    s = np.arange(e2.size)
    s2 = (np.arange(e2.size)+0.5) * (np.pi/e2.size)
    for i in range(e2.shape[0]):
        e2[i] = np.sum(e2 * np.cos(s2*i))
    e[i] = e2
e

array([[ 1.        ,  0.8660254 , -0.3660254 ],
       [ 1.        ,  0.8660254 , -0.3660254 ],
       [ 1.5       ,  1.6160254 , -1.04903811]])